### ISSUE TITLE
[2.0.2] published package is broken

### ISSUE THREAD

**Issue by AviVahl** [Rich-Harris/vlq#17]
- `import` entrypoint is broken. as `src` folder is not included in published npm package.
- `require` entrypoint is broken. `dist/index.js` should be renamed to `dist/index.cjs` for it to be forced as commonjs under a `"type": "module"` package. 

FYI @Rich-Harris

**Comment by Rich-Harris** [comment]
whoops, i updated `main` but not `exports`. fixed
