### ISSUE TITLE
[2.0.3] No dist/index.js for "require('vlq')" to work

### ISSUE THREAD

**Issue by SnarkBoojum** [Rich-Harris/vlq#18]
Trying to update the Debian package of vlq to 2.0.3, I see package.json says "require" should look for "dist/index.js", but after running rollup -c and tsc, one doesn't have such a file (unless there's something wrong with my setup).

**Comment by Rich-Harris** [comment]
ah whoops, fixed — thanks

**Comment by SnarkBoojum** [comment]
Thanks !
